### PR TITLE
Segfault when undefining field using element template.

### PR DESCRIPTION
**Pull request by hsorby**

### CODE REVIEW

**Comment by hsorby** [comment]
I have found that the segfault occurs if I try to undefine the *coordinate field* from the `fieldmodule/simple_1d_element.exf` mesh which has only one element and one finite element field. I have also found that if I set the field managed state to false then the segfault does **not** occur as the field is properly cleaned up when it leaves the scope where undefining the field takes place.

**Comment by rchristie** [comment]
I've been debugging it this morning. It seems the field I'm undefining, 'coordinates', is still holding on to mesh field data after the field should be undefined. I've also got it down to failing with a single 1-D element with 2 fields, but it only crashes if the field is also undefined at the nodes.

**Comment by rchristie** [comment]
I notice void FE_mesh::clearElementFieldData() writes the following twice during cleanup:
FE_mesh::clearElementFieldData.  Not all mesh field templates removed

**Comment by rchristie** [comment]
I think I see the problem. FE_mesh owns the mesh field templates; FE_field has references to them per-component. Need to ensure the destruction of the FE_mesh -- which precedes the destruction of the FE_field in this case -- causes the mesh field templates to be detached from the FE_mesh, so the FE_field doesn't need to involve the mesh in its clean-up.
This particular combination of cleanup issues comes about because the destruction of the computed field wrapper causes the FE_field to be removed from the region (as it's not used by any elements or nodes), but remains in the change log until the very end; the mesh clean-up is relying on asking the fields to detach their mesh field templates, but in this case the field isn't in the FE_region any more.
A related issue is why the FE_field doesn't clear the mesh field template when it's not defined anywhere....

**Comment by rchristie** [comment]
FYI If I rewrote this code I would not share mesh field templates between fields; instead each field would own it's own private template for all components. The mesh field templates are painful to share, requiring copy-on-write if you change one field and costly comparisons. It's no good for a serialisation concept has all fields need to talk to each other.

**Pull request closed without merging**
