### PR TITLE
Implement cubic Hermite serendipity basis

### LINKED ISSUE #109: Add 2-D and 3-D cubic Hermite Serendipity basis functions
Tensor products of Hermite bases have the drawback of needing cross derivative parameters which are both difficult to interpret and increase the number of degrees of freedom. Making a reduced Hermite basis by naively zeroing coefficients of cross derivatives gives a physically attractive result but the resulting basis has non-optimal approximation power due it its use of overly high-order monomial terms while neglecting some mid-order terms.

The cubic Hermite Serendipity bases eliminate the cross derivative parameters and define all remaining basis functions using only using monomial terms of up-to superlinear degree 3 (defined as the sum of powers of products of element coordinates x, y, z less the number of linear appearing variables, e.g. x(y^3) is order 3 but (x^2)(y^2) is order 4), which are associated with optimal approximation power. These bases satisfy the properties on the edges giving corner position and derivative parameters their same interpretation, but have subtly different internal shapes.

### PR DESCRIPTION
**Pull request by rchristie**
Closes #109.

### CODE REVIEW

**Comment by rchristie** [comment]
@alan-wu would you be able to review this?

**Comment by alan-wu** [comment]
Sure, I missed the notification on this...

**Comment by rchristie** [comment]
Sorry – had thought it would have automatically gone to you.
Would appreciate if you could review.

**Review by alan-wu — APPROVED** [review]
Looks fine to me.

**Pull request merged**
